-- return {
--   {
--     "echasnovski/mini.pairs",
--     event = "VeryLazy",
--     -- opts = {},
--     enabled = false,
--   },
--   {
--     "windwp/nvim-autopairs",
--     event = "LazyFile",
--     opts = {}, -- this is equalent to setup({}) function
--     enabled = true,
--   },
--   {
--     "windwp/nvim-ts-autotag",
--     dependencies = {
--       "nvim-treesitter/nvim-treesitter",
--     },
--     enabled = true,
--     event = "FileType typescriptreact,javascriptreact,vue,html,xml,astro",
--     config = function()
--       require("nvim-treesitter.configs").setup({
--         autotag = {
--           enable = true,
--           enable_close_on_slash = false,
--         },
--       })
--     end,
--   },
-- }
